# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.firefox.service import Service
import unittest

class UntitledTestCase(unittest.TestCase):
    def setUp(self):
        service = Service(executable_path="C:\\Windows\\SysWOW64\\geckodriver.exe")
        self.wd = webdriver.Firefox()
        self.wd.implicitly_wait(30)

    def test_untitled_test_case(self):
        wd = self.wd
        wd.get("http://localhost/addressbook/")
        wd.find_element(By.NAME,"user").click()
        wd.find_element(By.NAME, "user").clear()
        wd.find_element(By.NAME,"user").send_keys("admin")
        wd.find_element(By.NAME,"pass").click()
        wd.find_element(By.NAME,"pass").clear()
        wd.find_element(By.NAME,"pass").send_keys("secret")
        wd.find_element(By.XPATH, "//input[@value='Login']").click()
        wd.find_element(By.LINK_TEXT,"add new").click()
        wd.find_element(By.NAME,"firstname").click()
        wd.find_element(By.NAME,"firstname").clear()
        wd.find_element(By.NAME,"firstname").send_keys("Sabrina")
        wd.find_element(By.NAME,"middlename").click()
        wd.find_element(By.NAME,"middlename").clear()
        wd.find_element(By.NAME,"middlename").send_keys("Mark")
        wd.find_element(By.NAME,"lastname").click()
        wd.find_element(By.NAME,"lastname").clear()
        wd.find_element(By.NAME,"lastname").send_keys("Adamson")
        wd.find_element(By.NAME,"nickname").click()
        wd.find_element(By.NAME,"nickname").clear()
        wd.find_element(By.NAME,"nickname").send_keys("S@_brin@")
        wd.find_element(By.NAME,"title").click()
        wd.find_element(By.NAME,"title").clear()
        wd.find_element(By.NAME,"title").send_keys("worker")
        wd.find_element(By.NAME,"company").click()
        wd.find_element(By.NAME,"company").clear()
        wd.find_element(By.NAME,"company").send_keys("Froffice")
        wd.find_element(By.NAME,"address").click()
        wd.find_element(By.NAME,"address").clear()
        wd.find_element(By.NAME,"address").send_keys("34e, Lenina Street, 5, Omsk, Russia")
        wd.find_element(By.NAME,"home").click()
        wd.find_element(By.NAME,"home").clear()
        wd.find_element(By.NAME,"home").send_keys("-")
        wd.find_element(By.NAME,"mobile").click()
        wd.find_element(By.NAME,"mobile").clear()
        wd.find_element(By.NAME,"mobile").send_keys("7(978) 199-08-09")
        wd.find_element(By.NAME,"work").click()
        wd.find_element(By.NAME,"work").clear()
        wd.find_element(By.NAME,"work").send_keys("7(999) 100-99-99")
        wd.find_element(By.NAME,"fax").click()
        wd.find_element(By.NAME,"fax").clear()
        wd.find_element(By.NAME,"fax").send_keys("(499) 772-5189")
        wd.find_element(By.NAME,"email").click()
        wd.find_element(By.NAME,"email").clear()
        wd.find_element(By.NAME,"email").send_keys("SabrinaAdamson@mail.ru")
        wd.find_element(By.NAME,"email2").click()
        wd.find_element(By.NAME,"email2").clear()
        wd.find_element(By.NAME,"email2").send_keys("-")
        wd.find_element(By.NAME,"email3").click()
        wd.find_element(By.NAME,"email3").clear()
        wd.find_element(By.NAME,"email3").send_keys("-")
        wd.find_element(By.NAME,"homepage").click()
        wd.find_element(By.NAME,"homepage").clear()
        wd.find_element(By.NAME,"homepage").send_keys("-")
        wd.find_element(By.NAME,"bday").click()
        Select(wd.find_element(By.NAME,"bday")).select_by_visible_text("10")
        wd.find_element(By.XPATH,"//option[@value='10']").click()
        wd.find_element(By.NAME,"bmonth").click()
        Select(wd.find_element(By.NAME,"bmonth")).select_by_visible_text("June")
        wd.find_element(By.XPATH,"//option[@value='June']").click()
        wd.find_element(By.NAME,"byear").click()
        wd.find_element(By.NAME,"byear").clear()
        wd.find_element(By.NAME,"byear").send_keys("1996")
        wd.find_element(By.NAME,"aday").click()
        Select(wd.find_element(By.NAME,"aday")).select_by_visible_text("10")
        wd.find_element(By.XPATH,"//div[@id='content']/form/select[3]/option[12]").click()
        wd.find_element(By.NAME,"amonth").click()
        Select(wd.find_element(By.NAME,"amonth")).select_by_visible_text("June")
        wd.find_element(By.XPATH,"//div[@id='content']/form/select[4]/option[7]").click()
        wd.find_element(By.NAME,"ayear").click()
        wd.find_element(By.NAME,"ayear").clear()
        wd.find_element(By.NAME,"ayear").send_keys("2026")
        wd.find_element(By.NAME,"theform").submit()
        wd.find_element(By.LINK_TEXT,"Logout").click()

    def tearDown(self):
        self.wd.quit()

if __name__ == "__main__":
    unittest.main()
